### ISSUE TITLE
Is there any new template for 4.18?

### ISSUE THREAD

**Issue by sambuev** [google-ar/arcore-unreal-sdk#1]
Hello, I want to start developing production application with ARCore, I have tested the sample pack, but I want to know more, is there any other template that supports 4.18 and ready for production? Having the proper starter pack would help to lots of developers with their beginnings.

**Comment by bopangzz** [comment]
Hi, the current version of HelloAR sample should work with Unreal 4.18, so you can use that to get start on your development. However be aware that the ARCore support in 4.18 is still a developer preview version, it is not intended for use in production apps shipped to customers.

**Comment by Calence** [comment]
Hi , I want to know the different between ARCore.aar and Tango SDK. 
I know ARCore is supported by Google Pixel and some Samsung.
Tango SDK is only supported by PHAB2 Pro and PHAB2,  but when UE4 integrates Tango SDK, how to mudifly?

**Comment by Calence** [comment]
Excuse me, when I opened this master by 4.18 UE4 editor,it showed "Missing HelloARUnreal Modules"!
The following modules are missing or built with a different engine version:

UE4Editor-HelloARUnreal.dylib

Would you like to rebuild them now?

When I rebuild this ,the log is:
HelloARUnreal could not be compiled. Try rebuilding from source manually.

**Comment by bopangzz** [comment]
Hi, you probably got this error because you build the HelloAR project with a previous version of Unreal. Can you try download a clean repo of this HelloAR project and open it with Unreal UE4 and see if it fixed the problem.

To your early question, the developer preview version of ARCore in Unreal engine is built on top of the previous Tango SDK, that is why you were seeing a TangoSDK folder in the ThirdParty folder. What are you trying to figure out exactly?

**Comment by Calence** [comment]
To my early question , there are two devices(PHAB2 Pro and PHAB2) that support the Tango SDK, and different from Google ARCore devices (Google Pixel and so on). But after UE4 integrated Tango SDK, it can support devices is also Google Pixel, Pixel XL, Samsung, and so on, I want to know  whether is to modify the Tango SDK or not.  But I might have asked the wrong place....

**Comment by nathanmartz** [comment]
To be clear, the Tango SDK and ARCore SDKs are separate platforms. TangoSDK
requires phones with the Tango sensor suite, but ARCore works on regular
phones (currently Pixel and S8 with more coming). Our focus going forward
will be on ARCore, and that's what you'll see in our standard Unreal
integration.

**Comment by bopangzz** [comment]
Yeah, the Unreal Tango plugin is shipped with official Unreal 4.17 so if you are developing Tango platform, you should use that version of Unreal. The official Unreal 4.18 release remove the Tango plugin and added the GoogleARCore plugin so if you are developing ARCore platform, you can use the official Unreal 4.18 release. Google's [custom Unreal branch](https://github.com/google-ar-unreal/UnrealEngine) is based on Unreal 4.18 and it only contains the ARCore plugin.

**Comment by Calence** [comment]
Oh ! I has downloaded  official Unreal 4.18 release, I find it has been changed to GoogleARCore, but why it loads tango_client_api.so library. I guess it may be based on TangoSDK? The pictures are [Unreal4_18](https://github.com/Calence/messageNote/blob/master/res/Unreal4_18.png) ，[UE4_18_ARCore_Plugin](https://github.com/Calence/messageNote/blob/master/res/UE4_18_ARCore_Plugin.png)

**Comment by bopangzz** [comment]
Yeah, the dev preview version of Unreal GoogleARCore plugin is based on modified version TangoSDK right now.

**Comment by Calence** [comment]
Can I use the modified version TangoSDK? I also want to integrate the SDK into our project to achieve ARCore.Because ARCoreSDK is the Java version, it does't have C/C++ version.

**Comment by bopangzz** [comment]
Though ARCore is powered by Tango tech, the API is gonna be different. I think you probably should wait for ARCoreSDK the C/C++ API.

**Comment by Calence** [comment]
Will the Google official release API for the C/C++?Is there any official news?

**Comment by nathanmartz** [comment]
If you are interested in ARCore then just use 4.18 and we'll keep updating
the integration as more of the platform comes online.

**Comment by Calence** [comment]
Hello,  when UE4 integrated Tango SDK in 4.18 , I don't find libtango_client_api.so,but when I integrate TangoSDK, it shows ‘I/TangoClientLibLoader: Pure Java path, not loading libtango_client_api.so at all.’. Why?

In addition, the log shows 
A/tango: jni_helper.cc:19 'vm' Must be non NULL
 A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 20637 (GLThread 1549)
 I/TangoClientLibLoader: Pure Java path, not loading libtango_client_api.so at all.

**Comment by bopangzz** [comment]
Are you trying to use the TangoSDK in UE4 and use that in your own engine? Which phone are you testing on?

**Comment by Calence** [comment]
Yes, I use Google Pixel XL that Android version is 8.0.0.

**Comment by Calence** [comment]
The problem solved ， the reason is that threads between threads are not synchronized.
