### ISSUE TITLE
arcore v1.1 in ue4.19 failed

### ISSUE THREAD

**Issue by belko-vasiliy** [google-ar/arcore-unreal-sdk#13]
I use arcore plugin in unreal engine 4. I used your quickstart guide for it. And when I was using arcore v1.0 in ue4.18, it was OK with everithing, but when I tried arcore v1.1 in ue4.19, it wasn't. So I don't know why arcore v1.1 in ue4.19 doesn't work on samsung s7e sm-g935fd
[Log.txt](https://github.com/google-ar/arcore-unreal-sdk/files/1950170/Log.txt)

**Comment by bopangzz** [comment]
Hi, can you describe what happened after you start the HelloAR app? Is there any error message on the screen?

**Comment by belko-vasiliy** [comment]
Hello! When I debug project (or even if I've start packajed apk ), it works, but when it starts enum of GetARSessionStatus - not supported.

**Comment by bopangzz** [comment]
Can you capture another logcat and don't apply the "UE4" filter in the logcat this time? There might be some useful information there.

**Comment by belko-vasiliy** [comment]
When I cloned the google-ar-unreal repo and downloaded sample project  in another time, it starts working. Cleaning and full rebuild resolved my problem. Sorry for disturbance.

**Comment by bopangzz** [comment]
Glad you got it working again! Closing this bug.
