### ISSUE TITLE
HelloAR sample app won't work on One Plus 3T

### ISSUE THREAD

**Issue by CormacAsGaeilge** [google-ar/arcore-unreal-sdk#15]
I have gone through the steps on building Unreal with ARCore 1.2 from source. Unreal built fine and I loaded the sample HelloAR and it built successful but after pushing to my One plus 3T, the app still displays a message saying it does not support ARCore. 

ARCore 1.2 is installed and marked as officially supported now by ARCore. If I'm missing something obvious I'd be happy to find out. Thanks.

**Comment by bopangzz** [comment]
Which version of Android is you One plus 3T on?

**Comment by CormacAsGaeilge** [comment]
8.0.0

**Comment by bopangzz** [comment]
Hmm, can you attach a logcat when running the Unreal HelloAR sample?

**Comment by bopangzz** [comment]
@CormacAsGaeilge Can you provide a logcat **without** UE4 filtering?

**Comment by CormacAsGaeilge** [comment]
Apologies, I haven't had a chance to come back to my ARCore project. I will post a logcat shortly.

**Comment by bopangzz** [comment]
Closing the issue due to lack of response. Feel free to reopen if the issue still exists.
