### ISSUE TITLE
ARCore so slow

### ISSUE THREAD

**Issue by GSoria3D** [google-ar/arcore-unreal-sdk#18]
Hello and first of all, thanks!
I'm creating a game with ARCore with UE4. You must throw balls to a paper bin. After seconds, the game is so slow. I'm using physics to throw balls and simple colliders for the paper bin, balls and ground. Any suggest?

**Comment by bopangzz** [comment]
Which phone you are testing on? Have you tried play your game without ARCore and see the performance?

**Comment by sambuev** [comment]
I don't think ARCore is slow, maybe you have an event on Tick which creates an unlimited number of UMG or some other events which kill the performance after seconds.

**Comment by bopangzz** [comment]
Closing this issue due to lack of response. Feel free to reopen it if it still happens for you.
