### ISSUE TITLE
Augmented Images project can't be built with 4.19

### ISSUE THREAD

**Issue by alexandreMarie** [google-ar/arcore-unreal-sdk#19]
Hi, 

I've cloned the google-ar-unreal/UnrealEngine repos and trying to build the augmented images project.

[ARCore_AugmentedImages_Errors.txt](https://github.com/google-ar/arcore-unreal-sdk/files/2079602/ARCore_AugmentedImages_Errors.txt)

So I'm pratically sure that I've missed something or bad install one or another thing.

If someone had already succeed it. Can you please tell me how you done it ?

Best Regards,

Alexandre

**Comment by bopangzz** [comment]
HI, it looks like the blueprint is corrupt.  When you open the project in Unreal Editor, it probably will ask the project is built with a different version of Engine, what you want to do? Did you skip the conversion there? If so can you try git reset your sdk repo and open the project again and select convert in place this time?

If you already convert the project, can you try open that TrackingStateOverlay.uasset blueprint and see if you see any compile error?

**Comment by sambuev** [comment]
I was able to build with no problems, I currently work with Augmented-Images demo, it just has few limitations:

1. Minimum size 15x15cm
2. Tracked Image doesn't help other relative objects to get better tracking. 
3. No moving images
4. Only front angle is working
5. Tracking points around the image don't help the image to get better align, this is why it's going to jiggle around constantly.

**Comment by alexandreMarie** [comment]
So yes I've made a reset and it works properly. No idea why. :s
