### ISSUE TITLE
4.18 Asking to rebuild HelloARUnreal.dll

### ISSUE THREAD

**Issue by sambuev** [google-ar/arcore-unreal-sdk#2]
I've downloaded the project file and trying to open in 4.18.2 and it showing me a window with Missing HelloARUnreal Modules and asking Would you like to rebuild them now? And even when I say Yes it can't compile. How to fix it please?

**Comment by ArthurBarthur** [comment]
Can you try building the engine from source, in accordance with all the instructions, not forgetting any linked sub-instructions? Are you on VS2015?

**Comment by bopangzz** [comment]
@sambuev  Which version of Unreal Engine you are using? The current head of the HelloARUnreal project require the ARCore Dev Preview 2 version of Unreal ARCore Plugin to compile, which you can find it here: https://github.com/google-ar-unreal/UnrealEngine

If you are on the official Unreal 4.18.2, you should use the previous release of HelloARUnreal: https://github.com/google-ar/arcore-unreal-sdk/releases/tag/sdk-preview

**Comment by raMaa026** [comment]
Hi. I'm having the same issue as sambuev had. I have both versions of UE 4.17.2 and 4.18.2.  The first link that is posted by bopangzz  is not working. It's the same link on official AR page which is also not working. Can it be posted again or is there any workaround. I just can't get it installed. Thank you.

**Comment by bopangzz** [comment]
@raMaa026  If the link isn't working for you, it means you don't have Unreal source code access on your github account. You can follow the instruction there to link your github account with your Epic account to get access.

**Comment by raMaa026** [comment]
@bopangzz Right.I've skipped that part indeed. I just completed it, but the page is still not accessible.Do I need to wait till this is checked or...? Thank you

**Comment by raMaa026** [comment]
@bopangzz Me again. I got it all installed this till the point where I need to Generate project files. I've ran it all in administrative mode, downloaded all files 3 times and tried it 3 times. But I'm getting this error. There is no antivirus software installed.
![error2](https://user-images.githubusercontent.com/35292294/34835199-1293999e-f6ec-11e7-8392-1f2122347dbd.jpg)

**Comment by bopangzz** [comment]
@raMaa026 Have you ran Setup.bat before running GenerateProjectFile?

**Comment by raMaa026** [comment]
Yes I did and it was done with no errors

**Comment by bopangzz** [comment]
It looks like somehow the directory path is messed up. Can you show me how did you run GenerateProjectFile script?

**Comment by raMaa026** [comment]
I just right clicked on it run as administrator and that was it

**Comment by bopangzz** [comment]
Is there a UnrealBuildTool.exe under you C:\ folder? Looking at the AddEngineShaderSource function in ProjectFileGenerator.cs, it seems the UnrealBuildTool.EngineDirectory somehow become "C:\Engine" where it should be under the UnrealEngine folder on in your Desktop folder.

**Comment by raMaa026** [comment]
I will have to come back to you with answer tomorrow because all my files are at work. Don't have anything at home atm. So do I need to have UnrealBuildTool.exe in downloaded folder that I got from here or in the root folder of the UE4?

**Comment by bopangzz** [comment]
The UnrealBuildTool.exe should be in this "YOUR_USER_FOLDER/Desktop/UnrealEngine/Engine/Binaries/DotNET". If it is there, you probably need to debug this on your machine by adding some log in ProjectFileGenerator.cs to see why the path got wrong.

**Comment by raMaa026** [comment]
Thanks I will investigate this tomorrow so.
