### ISSUE TITLE
Image Tracking based on device position

### ISSUE THREAD

**Issue by alexandreMarie** [google-ar/arcore-unreal-sdk#20]
Hi everyone,

ARCore image tracking set the transform of the tracked geometry based on the device position and not based on the image itself. I'm sure i'm missing something to configure it well but it's really annoying. If anyone successfuly made it, it could be really helpfull.

Best regards,

Alexandre

**Comment by bopangzz** [comment]
I am not sure what do you mean by that, can you elaborate? Also have you
checked out our Augmented Image sample?

**Comment by alexandreMarie** [comment]
I have my image placed on a table and if i'm coming from the left side of the image, the transform will not be the same than if I'm coming from the bottom of the image. I've joined a picture to explain.

And yes I made my project based on the Augmented Image sample
![plan](https://user-images.githubusercontent.com/12408986/41358466-b3f5f9ee-6f28-11e8-96f0-a11b47ac3b64.png)

**Comment by bopangzz** [comment]
Hmm, are those different transforms from the same session? Have you tried the same code on a image from the Augmented Images sample? I wonder if the image looks too similar on different angle?

And just to confirm, how did you get the transform? Are you using the TrackedGeometry.GetLocalToWorldTransform?

**Comment by alexandreMarie** [comment]
Yes It's from the same session and also yes I'm using the TrackedGeometry.GetLocalToWorld function. And this marker had a score of 100 in ARCoreImg. But I'm going to test with the earth image from the sample database.

**Comment by alexandreMarie** [comment]
So I've just tested with the earth image and yes same results.

**Comment by alexandreMarie** [comment]
So there was a mismatch, I was using the world rotation instead of the tracked geometry rotation (now I've printed the forward, right and up vector I see it works actually even if it does not match the Unreal transform ( you know the thing that Z is the up vector -_-" ) ).

This was the bluprint which saved me :

![drawdebugtransform](https://user-images.githubusercontent.com/12408986/41405074-2c0f8e86-6fc9-11e8-97db-87a3ff99062c.png)
