### ISSUE TITLE
Issue while package : ARCore 1.2 in UE 4.19

### ISSUE THREAD

**Issue by manuganu9** [google-ar/arcore-unreal-sdk#22]
I had build Unreal Engine 4.19 from **https://github.com/google-ar-unreal/UnrealEngine** for ARCore 1.2.1.
I had download Sample Project from **git clone https://github.com/google-ar/arcore-unreal-sdk.git**.

Now I am unable to package HelloARUnreal Sample Project.

This is Log File : 
[HelloARUnreal_2.log](https://github.com/google-ar/arcore-unreal-sdk/files/2101042/HelloARUnreal_2.log)

**Comment by alexandreMarie** [comment]
Did you setup everything has said in :

https://developers.google.com/ar/develop/unreal/quickstart

CodeWorks, 
adding SDK, NDK locations in Edit->ProjectSettings->Android SDK ?

**Comment by bopangzz** [comment]
@manuganu9 It looks like you are using ndk 15b, which I believe isn't supported in UE4.19 yet. You might need to use Ndk r13.

**Comment by bopangzz** [comment]
Closing the issue due to lack of response. Feel free to reopen if the issue still exists.
