### ISSUE TITLE
Packaged app not working on Moto G5S Plus

### ISSUE THREAD

**Issue by manuganu9** [google-ar/arcore-unreal-sdk#24]
I have packaged app in unreal engine.but it is not working on my Moto G5S Plus.

Recently it is included in supported devices recently.

My app is working perfectly in Pixel.

Is there any solution for it?

**Comment by manuganu9** [comment]
I have used Unreal engine 4.19 with ARCore SDK 1.2.1 which is given in ARcore with Unreal engine.(official ARCore site)

**Comment by bopangzz** [comment]
Can you attach a logcat of a development build running on Moto G55?

**Comment by manuganu9** [comment]
[Log.txt](https://github.com/google-ar/arcore-unreal-sdk/files/2111206/Log.txt)

Generated Log file while lunching project on Moto G5S Plus.

**Comment by manuganu9** [comment]
[UAT_Log.txt](https://github.com/google-ar/arcore-unreal-sdk/files/2111243/UAT_Log.txt)

UAT Log file.

**Comment by bopangzz** [comment]
Ah, I think I know the problem. So Moto G55 may not support 64bit build. Can you try uncheck arm64 and check armv7 checkbox under Project Settings->Androids and package the sample again?

**Comment by bopangzz** [comment]
Closing the issue due to lack of response. Feel free to reopen if the issue still exists.
