### ISSUE TITLE
Poor camera quality when passing in C++

### ISSUE THREAD

**Issue by alexandreMarie** [google-ar/arcore-unreal-sdk#25]
Hi everyone,

I've successfully made my ARTemplate project in C++ (woohoo...) But since the camera is **blurred** and it became much more difficult to track an image. The weird thing is I have a better quality if I use BP.

Does someone know where to or how to configure that ?

Best regards,

Alexandre

**Comment by bopangzz** [comment]
That is really wired. C++/Blueprint shouldn't affect the background image rendering. Did you do anything different to render the camera image in your c++ project?

**Comment by alexandreMarie** [comment]
Nope just the same pipeline for starting ARCore session than in the AgmentedImage project. But i've started it from blank c++ project so maybe I've missed a parameter where I can choose the resolution of the camera or set autofocus... That doesn't remind you a parameter ?

Thanks for  the reply btw.

**Comment by bopangzz** [comment]
Do you mind send me a project to reproduce the issue? There is no camera resolution configuration yet in GoogleARCore Unreal plugin. It is a fixed 1920x1080 resolution for camera texture right now.

**Comment by alexandreMarie** [comment]
It seems to be more like a focus problem. But yes how can I send it to you ?

**Comment by bopangzz** [comment]
@alexandreMarie Can you upload it to a Google drive and share the link here?

**Comment by alexandreMarie** [comment]
https://drive.google.com/file/d/1I0H7cDtQOUE1hZ7EREDJFw7x-uICesLI/view?usp=sharing

**Comment by alexandreMarie** [comment]
![screenshot_20180629-094931_augmentedimages 1](https://user-images.githubusercontent.com/12408986/42080175-11978f76-7b82-11e8-8a85-e25b44494626.jpg)
![screenshot_20180629-094953_artemplatecpp 1](https://user-images.githubusercontent.com/12408986/42080188-1dc3cf76-7b82-11e8-83cc-637841d8b64a.jpg)

The brighter and blurred one is from the CPP project and the darker is from the BP project.

But for now I will let this thread on stand by because my client want this to turn on tablet. And I will have to move to ARKit to use iPad. :/

**Comment by bopangzz** [comment]
@alexandreMarie Looking at the screenshot, it looks like your CPP project has mobile HDR turned on in project settings. The camera texture is rendered in linear color space when mobile HDR is on so you will have to tonemap the frame output to gamma space. We recommend to turn off mobile HDR in general unless there is a specific use case in your app.

**Comment by alexandreMarie** [comment]
Thanks @bopangzz ! It was that :)
