### ISSUE TITLE
Check if arcore is supported.

### ISSUE THREAD

**Issue by MrMcKvarz** [google-ar/arcore-unreal-sdk#26]
When checking device, that does not support arcore it returns SupportedNotInstalled, instead of UnsupportedDeviceNotCapable.

**Comment by bopangzz** [comment]
Which phone are you testing on? You get SupportedNotInstalled if the phone is supported by the ARCore apk isn't installed.

**Comment by MrMcKvarz** [comment]
Xiaomi mi a1, I get SupportedNotInstalled, then proceed to start AR session and arcore says that I need to install arcore, redirect to arcore play market page, which says your device is not supported.

**Comment by bopangzz** [comment]
@inio Any idea?

**Comment by inio** [comment]
You’re right, it should.  That doesn’t make sense.  If you could capture a logcat that would be helpful.

**Comment by dev4711** [comment]
Same issue for Asus ZenFon3, with Android 7. Get from the checkAvailability(this) SUPPORTED_NOT_INSTALLED but when opening arcore in the playstore to install, cant install and get the message "your device isn't compatible with this version".

**Comment by bopangzz** [comment]
Close the issue due to lack of response. Please reopen if the issue still exist.
