### ISSUE TITLE
HelloAR stuck at 95% loading. 

### ISSUE THREAD

**Issue by moothyknight** [google-ar/arcore-unreal-sdk#27]
Hey, not sure what the deal is with the HelloAR demo but it won't load. It gets stuck at 95% and then eats up all the CPU resources. I'm on Windows 10 and am using the 1.3 fork. The other demos work just fine and built correctly on the S8 I'm using.

**Comment by bopangzz** [comment]
Can you attach a Android logcat?

**Comment by moothyknight** [comment]
It's happening in the Editor on the computer, not on the phone.  Attaching a screenshot
![capture](https://user-images.githubusercontent.com/18196383/42182824-fe076c8a-7deb-11e8-836c-d9186989bcd1.PNG)

**Comment by moothyknight** [comment]
Okay, well after using the most up to date Unreal 4.20 client today, and ensuring my computer was up to date, it works! I won't question it.

**Comment by moothyknight** [comment]
Well it opened in 4.20 and I got it to compile after the second try, so mystery... solved?

**Comment by bopangzz** [comment]
The stuck you saw is probably converting the project somehow triggered a full compilation of the entire Unreal Engine, which could take a while. If it happens again, you should be able to check the log file under ProjectFolder/Saved to see what it is doing.
