### ISSUE TITLE
Shadows are present only on specific angle of the device

### ISSUE THREAD

**Issue by alexandreMarie** [google-ar/arcore-unreal-sdk#29]
Hi everyone,

I've finished my application but one problem subsists.

This is what I want :

![arscreenshot_web](https://user-images.githubusercontent.com/12408986/42495936-caee9118-8424-11e8-9ac5-da1ea6b9711d.jpg)

And if you move just the device a little : 

![arscreenshot_2_web](https://user-images.githubusercontent.com/12408986/42495965-e7a8c062-8424-11e8-9d14-a30194a8b257.jpg)

It's clearly a problem of angle because if I maintain this orientation and go far fo the model or close to, the shadows are here. It's really if I'm moving around, all the shadows disapear.

Anyone had this problem and knows how to avoid it ?

Alexandre

**Comment by bopangzz** [comment]
What GLES level you are using in your app? Have you tried use the other one? I know there were some weird shadow issue on GLES 3.1 in the previous version of Unreal.

Also can you try tp record those positions with this problem and try place the camera and your scene in the same spot and see if you can reproduce the issue in Unreal editor when setting preview level to the one you were using on your phone.

**Comment by alexandreMarie** [comment]
I'm currently using OpenGL ES2 I will try using OpenGL ES3.1. And I don't understand what you are meaning by record positions ? I have perfect shadows in the editor, no matter the orientation of the camera even in Game View mode.

Thanks for the reply by the way :D

Alexandre

**Comment by alexandreMarie** [comment]
So I tried both same results. And when I set "Settings"->"Preview Rendering Level"->"Mobile/HTML5"->"Android Preview" AND "High-End Mobile"->"Mobile OpenGLES 3.1" I have effectively no shadows. Which I don't understand because it should. My skylight is in Static with "No Cast Shadows" and one "Directionnal Light" with the following setup : 
![capture](https://user-images.githubusercontent.com/12408986/42938273-04f442ac-8b52-11e8-9e0a-98d6fdff7f00.PNG)

And all my models have this setup : "Movable" (of course I think) and "Receive CSM Shadows"
and this :
![capture2](https://user-images.githubusercontent.com/12408986/42938437-90203548-8b52-11e8-98e0-3cf61f582237.PNG)

**Comment by bopangzz** [comment]
Do you have Mobile HDR enabled? Modulated Shadow only works when Mobile HDR is enabled, if I remembered correctly. Also your light need to be stationary.

**Comment by alexandreMarie** [comment]
Unfortunately yes :( I will try to have Dynamic Shadows with stationnary lights because when I put my light in stationnary I have no shadows anymore.

**Comment by bopangzz** [comment]
Have you tried using dynamic shadow? It seems modulated shadow have some bug in Unreal 4.20.

**Comment by ulimon1** [comment]
Hello alexandreMarie,
i have a really stupid Question.
How did you replace the andy character? When i set up another static mesh than andy it only shows the blob shadow.

Greetings
Uli

**Comment by bopangzz** [comment]
I have verified both dynamic shadow and modulated shadow works fine with ARCore in Unreal 4.20. If you still find this is a problem, feel free to reopen this bug.
