### ISSUE TITLE
Error in UE4.18.3

### ISSUE THREAD

**Issue by guo787269125** [google-ar/arcore-unreal-sdk#3]
I've downloaded this project and open it in UE4.18.3 (the GitHub version). I got "Recompile project from source". And Compile error. I cannot open it.
Which Engine version does this project support????

![qq 20180126122646](https://user-images.githubusercontent.com/7721473/35425230-51ab655e-0294-11e8-9f79-56df9ac69659.png)

**Comment by bopangzz** [comment]
Hi, the latest version of the project need our forked version of Unreal Engine: https://github.com/google-ar-unreal/UnrealEngine/tree/4.18-arcore-sdk-preview2

If you want to use Epic's Unreal 4.18.3, you can use the previous release of this project: https://github.com/google-ar/arcore-unreal-sdk/tree/sdk-preview
