### ISSUE TITLE
May i know how to update the plugin ARcore on UE4?

### ISSUE THREAD

**Issue by lyxuan007** [google-ar/arcore-unreal-sdk#32]
Sry i am a new-b at UE4 i very confuse how to update the plugin of  ARcore on UE4. I have found source code but i dont know how to use the source code to update the version can you specially it ? Thank you

**Comment by bopangzz** [comment]
I guess you want to use the latest ARCore plugin in Unreal? If that is the case, you will have to use the source code version of Unreal Engine on Google's ARCore branch, which you can clone the repo here:
https://github.com/google-ar-unreal/UnrealEngine

After you clone the repo, follow Epic's guide to build the Engine from the source code and you can start using the Engine you built with latest ARCore plugin.

Unfortunately there is no way to update the ARCore plugin in the binary version of Unreal Engine, which you download from Unreal Launcher.

**Comment by lyxuan007** [comment]
sry so late to reply your email, which mean i have to use git to clone the
source to my unreal engine? my UE4 download from epic and version 4.20. 1

**Comment by bopangzz** [comment]
I will have to use git to clone the engine source code to a new repo. It will become a different version of Unreal than the one you download from Epic Launcher.

**Comment by aussieburger** [comment]
FYI: The newly released binary version 4.20.2 includes a fix for the missing ARCore tools folder:

https://forums.unrealengine.com/unreal-engine/announcements-and-releases/1518874-4-20-2-hotfix-released

(see the last note).

If you don't use that version the you need to download the source and build it

**Comment by JaviTechnologies** [comment]
@bopangzz do you know if I proceed with this option, Unreal would still support ARKit?

I know this is an Unreal issue since they are trying to push their "Unified AR Framework". Which is limiting us a great deal! They are going to keep us behind the latest technologies most of the time.

I miss Unity so much. Not in my hands to change to it :(

**Comment by bopangzz** [comment]
Yeah, you can use ARKit if you use Google's ARCore branch. We keep update our branch with the latest Epic release of Unreal so it should have the same version or ARKit plugin as the one on Epic's branch.

**Comment by vatro** [comment]
> Yeah, you can use ARKit if you use Google's ARCore branch. We keep update our branch with the latest Epic release of Unreal so it should have the same version or ARKit plugin as the one on Epic's branch.

Could you please update to **4.20.3** (released on 19.09.2018 https://github.com/EpicGames/UnrealEngine/commit/5e997dc7b5a4efb7f1be22fa8c4875c9c0034394) then? Currently it is still based on 4.20.2 Thanks! 👍😁
