### ISSUE TITLE
x86 supported?

### ISSUE THREAD

**Issue by LowIQAnon** [google-ar/arcore-unreal-sdk#33]
I was wondering whether it is already, or will be possible to build the HelloAR sample for x86 in the near future? 

From what i have read, [x86 is supported in the arcore-android-sdk since 1.0](https://github.com/google-ar/arcore-android-sdk/issues/138#issuecomment-368075696). Does this apply to the unreal-sdk also?

I might just be making mistakes in the build process. So far i've tried using both the 1R6 and 1R7 Codeworks for Android bundles as suggested by the unreal documentation, as well as manually getting the most recent SDK and NDK versions and targeting for numerous emulated devices and API levels. I did also build the Unreal Engine from the google-ar-unreal/UnrealEngine repository.

I currently run into "static_assert failed" errors, for instance:
`LogPlayLevel:   PLATFORM_ANDROID_NDK_VERSION = 150300`
`LogPlayLevel:   NDK toolchain: r15c, NDK version: 26, GccVersion: 4.9, ClangVersion: 5.0.300080`
[...] 
`
LogPlayLevel:   C:/Epic Games/UnrealEngine/Engine/Source/Runtime/Core/Public/HAL/Platform.h(798,2):  error: static_assert failed "Pointer size is 32bit, but pointers are long."
LogPlayLevel:           static_assert(PLATFORM_64BITS || sizeof(void*) == 4, "Pointer size is 32bit, but pointers are long.");
`

Any help would be much appreciated.

**Comment by bopangzz** [comment]
The GoogleARCore plugin should hooked up x86 build already. The error you saw is more likely on the Unreal Engine side. Have you tried build the third person template without ARCore plugin in x86 see if it works? It not, you probably want to report the issue to Epic.

**Comment by LowIQAnon** [comment]
Duh. I do have the same error with the general UE samples. Thanks, I will further look into it through Epic's channels.
