### ISSUE TITLE
GoogleARCoreServices plugin could not be found

### ISSUE THREAD

**Issue by slowizzm** [google-ar/arcore-unreal-sdk#34]
I am trying to open the CloudARPin project, but the GoogleARCoreServices plugin is missing. I have tried to follow the links to the repo, but find myself at a 404. Where might I find an available download?

**Comment by slowizzm** [comment]
@bopangzz thanks, I will try to use the one from the source. 

I was wondering if the 404 was due to not having access. I went through those steps a couple times now and github seems to not want to connect on unReals end.

**Comment by bopangzz** [comment]
You should get an email to ask you to join Epic's GitHub organization once you connect your github account to your epic account. You should have access once you join the organization.

**Comment by slowizzm** [comment]
Thanks, I will keep an eye out for that.

**Comment by slowizzm** [comment]
Issue resolved.

The invitation was available on github, email came after I accepted. I was able to download 4.20arcore, build, and load editor via VS with plugin included. 

thanks

**Comment by bopangzz** [comment]
Glad it works for you! Closing the bug now.
