### ISSUE TITLE
Hosting Error:ErrorNotAuthorized

### ISSUE THREAD

**Issue by slowizzm** [google-ar/arcore-unreal-sdk#35]
I have built the CloudARPin example to both android and iOS, but I am getting a `Hosting Error:ErrorNotAuthorized` on both devices when I try to host. This happens right after I place the pin. I added an API key to the android build, but not the ios build, should I add the same key to both, or remove the API key from android build? I'm not too new to AR dev, but I am kind of new to the cloud side of AR dev.

UnrealEngine-4.20-arcore
Samsung s9 version 8.0
iPhone 11 version 11.4

**Comment by bopangzz** [comment]
Yeah, you should add API key to both iOS and Android field. Whether you can use the same API key depends on how you setup your API key. If it is an unrestricted API key, you can use the same key for both Android and IOS. Otherwise, you need two different keys for different platform.

**Comment by slowizzm** [comment]
Thanks, that makes sense. I have added my API key, which is unrestricted, to both android and ios ... but I still receive the `Hosting Error:ErrorNotAuthorized`.

I see nothing in my Output log that would indicate any issue or direct me down a path to solve the issue.

**Comment by slowizzm** [comment]
Ahh ... that was it. I originally enabkes it, I thought, but just checked and it was disabled. 

Working now. Issue resolved. 

Thank you.

**Comment by slowizzm** [comment]
Before this get closed, and maybe I should open a new issue for this ...

I am able to host a session from each device, but I am not able to join the session from the other (tried both ways). What would be causing this failure to join?

**Comment by slowizzm** [comment]
I have only tried android to ios, I can try android to android as well as ios to ios tmrw at the office. I am on the same network, not 100% if my network allows p2p, I was just looking into that, do you know how I can confirm that it does or not?

**Comment by bopangzz** [comment]
You can try ping other phone using its ip address using "adb shell ping" and see if it can success.

**Comment by slowizzm** [comment]
Yes, deff allows p2p ... I was able to ping my device.

**Comment by slowizzm** [comment]
Got it to work on iOS to iOS, so I will close this issue. If you can point me toward some documentation and/or example projects that have a work around for connecting android and iOS devices, that would be appreciated. 

Thanks for your help.

**Comment by bopangzz** [comment]
I think the connection issue between Android and iOS is only an issue in 4.20, which I believe is introduced by Unreal upgrade iOS ip address to ipv6. You can try use some other network solution to pass around the Cloud ARPin ID. Or if you want to keep using local network, you can try use the 4.19-arcore branch which doesn't have the issue but 1 version behind.

**Comment by aussieburger** [comment]
https://github.com/google-ar/arcore-unreal-sdk/issues/35#issuecomment-419526790

@bopangzz will this be fixed in a future version of the plugin out of interest?

**Comment by bopangzz** [comment]
The issue is not in the Google ARCore Plugin but a Unreal Engine networking issue. Epic will have to fix the issue in future Engine releases.
