### ISSUE TITLE
Are there any plans to make moving augmented image support?

### ISSUE THREAD

**Issue by sambuev** [google-ar/arcore-unreal-sdk#36]
I would like to make an application with moving image support, such as magazine page, big moving advertising on a bus or just spinning disk with an image, 
Do you have any plans to support moving augmented images?

**Comment by sambuev** [comment]
Similar to ARKit 2.0. 

![6d303f5a-4900-4c3a-bf02-35ec326528f4](https://user-images.githubusercontent.com/6326685/46153081-71ef3e00-c240-11e8-875b-a2771906abb3.gif)

**Comment by bopangzz** [comment]
I will pass this feature request to the team.

**Comment by sambuev** [comment]
I would like to know the status? Did you add this feature to ARCore and UE4? 
Thanks.

**Comment by zyadmardini** [comment]
Has this feature been implemented yet ?
