### ISSUE TITLE
Ceiling Dectection in ARCore P2 & Unreal?

### ISSUE THREAD

**Issue by aussieburger** [google-ar/arcore-unreal-sdk#4]
Hi,

I was wondering if ceiling detection should be possible in ARCore Preview 2 UE4 plugin?
When testing https://github.com/google-ar-unreal/UnrealEngine/ (currently using 4.18.3) and this HelloARSample ceilings do not get detected.

Is this because ceiling detection has not yet been implemented? If that is the case is there any roadmap for when it will be added? If it is currently supported could you give some pointers how to get it working?

Thanks in advance for the info!

**Comment by bopangzz** [comment]
ARCore DP2 should be able to detect ceiling planes and it should be working in HelloARSample. My guess you are not seeing any ceiling plane because the ceiling you were trying to detect lack of feature point?

**Comment by aussieburger** [comment]
I really can't get it to work even with a lamp hanging from it and a ceiling skirting board. Would be great if you could double check it's working with that UE4 demo as I've not seen or heard of it working yet.

Assuming it's working but in general difficult to detect a plane white plane like that we should assume end users would find it too difficult to detect at their homes?

**Comment by bopangzz** [comment]
I tested yesterday and it was working for me. I assume you already using arcore-preview2.apk on your phone? Which device you are testing with? It might be helpful if you can share the HelloAR apk you built so I can test here.

**Comment by aussieburger** [comment]
I'm running a S8 and have the preview2.apk installed.

Here's a view of the ceiling where I tried to capture the edges in the hope it detected something:

![screenshot_20180202-224026](https://user-images.githubusercontent.com/8150481/35757270-a037113e-086e-11e8-99fd-56c91f839940.png)

and here is the exported apk (nothing changed on it):
https://1drv.ms/u/s!AixjdiALS4qujkaimJp5ct7ENEZ3

**Comment by bopangzz** [comment]
Your build is working for me. So I believe the problem is there isn't enough feature point on the ceiling to construct a plane, which you can also see from your screenshot.

**Comment by aussieburger** [comment]
Could you please provide a screenshot of a ceiling with enough feature points? Will help us determine if it's valid for the typical enduser once we know what angle/feature point is normally required.

Many thanks in advance!

**Comment by aussieburger** [comment]
@bopangzz  I guess I was hoping that the ridges on the ceiling (skirting board on the ceiling what ever that is called) would be enough to identify the plane - especially when I could match it on both sides. Do you ever think the plane detection will get advanced enough to work with ceilings like that?

**Comment by chaosemer** [comment]
The planes are detected on top of the feature points that we expose. If you do not see any feature points on the ceiling, we won'tbe able to detect the plane.

Honestly, the ceiling you're sharing has so few features that I don't see us detecting planes there for a while.

**Comment by aussieburger** [comment]
Ok thank you for the info!
