### ISSUE TITLE
AugmantedImages "get estimate size" node missing source

### ISSUE THREAD

**Issue by Wolgraph** [google-ar/arcore-unreal-sdk#40]
Cloned this release of augmantedimages project and I noticed in Level Blueprint "Get Estimate Size" can't compile. If I'm right it measure the tracked image size and use it to correctly place the frame corners. 
![cattura](https://user-images.githubusercontent.com/39592289/49700241-4ee7ef80-fbdc-11e8-9a98-4908f7db062e.PNG)
Any solution?

**Comment by bopangzz** [comment]
The Augmented Image sample in ARCore 1.6 release isn't compatible with Unreal 4.20.3 from Epic, as it uses our latest changes in GoogleARCore plugin to use the Unreal cross-platform api. You can:

Use ARCore 1.5 release if you want to use the Epic version of 4.20.3
Use our latest GoogleARCore plugin shipped with our forked version of Unreal Engine. You can find it here: https://github.com/google-ar-unreal/UnrealEngine
