### ISSUE TITLE
ARCore not detected the target image

### ISSUE THREAD

**Issue by worma27** [google-ar/arcore-unreal-sdk#41]
Hello,

I am totally new using AR core. I am now using AR core package 1.6 and UE 4.20.3.
I successfully build Augmented Images application on my mobile phone. 
I used Augmented Image sample file.
I have a problem when I try to scan the target image, nothing got tracked and nothing showed
on my screen.

What I am doing wrong?
Any advise?
Thank you in advance

![47579849_1931959573767734_2289144704647823360_n](https://user-images.githubusercontent.com/45752909/49719063-a47cd480-fc8e-11e8-87bf-e3846c368419.jpg)

**Comment by bopangzz** [comment]
The Augmented Image sample in ARCore 1.6 release isn't compatible with Unreal 4.20.3 from Epic, as it uses our latest changes in GoogleARCore plugin to use the Unreal cross-platform api. You can:

1. Use ARCore 1.5 release if you want to use the Epic version of 4.20.3
2. Use our latest GoogleARCore plugin shipped with our forked version of Unreal Engine. You can find it here: https://github.com/google-ar-unreal/UnrealEngine

**Comment by worma27** [comment]
Thank you. I have tried. Please help it error
![1](https://user-images.githubusercontent.com/45752909/49782431-e9fdd800-fd48-11e8-8ad9-0c56d8e58cec.JPG)

**Comment by bopangzz** [comment]
Can you describe what you have tried? Which version of Unreal Engine you end up using?

**Comment by worma27** [comment]
I use AugmentedImage example file from AR core package 1.5 and UE 4.20.3.
I copy the folder of AugmentedImage to a new folder and run it.
Then, set up in the project setting and lunch it. 

Can you please help?
What should I do?
What I set up is below

I also would like to know what UE version that is compatible with ARcore package 1.6? 

![3](https://user-images.githubusercontent.com/45752909/49807162-fce5cc00-fd8b-11e8-9fdf-1e22135bdac7.JPG)
![4](https://user-images.githubusercontent.com/45752909/49807170-00795300-fd8c-11e8-9ac4-cd75df0332d4.JPG)


![1](https://user-images.githubusercontent.com/45752909/49807030-abd5d800-fd8b-11e8-869a-b287ba6f7851.JPG)
![2](https://user-images.githubusercontent.com/45752909/49807036-b09a8c00-fd8b-11e8-98ca-9ef4dee57416.JPG)

**Comment by worma27** [comment]
I also try to remove Enable Gradle instead of Ant. 
It turns out like the picture below. I use Huawei Y9 2019.

![screenshot_20181211-215127 1](https://user-images.githubusercontent.com/45752909/49812260-99619b80-fd97-11e8-888e-dacf92ce9973.jpg)

**Comment by worma27** [comment]
I turn on Enable Gradle instead of Ant.

[Logcat.txt](https://github.com/google-ar/arcore-unreal-sdk/files/2670226/Logcat.txt)

**Comment by bopangzz** [comment]
So you got the error because the editor failed to cook the AugmentedImageDatabase. I would suggest you to switch to use our forked version of Unreal Engine with the latest GoogleARCore plugin. But you will have to build from source code. You can find the forked repo here: https://github.com/google-ar-unreal/UnrealEngine

If you would like to stay on the Epic's version, we need to figure out why the cooking process failed.

**Comment by worma27** [comment]
Thank you for your suggestions.
Finally, I successfully build my AR app.
![48372715_1864218933686847_307913090282815488_n](https://user-images.githubusercontent.com/45752909/49857353-e8a1dd80-fe24-11e8-8db3-1b1ffefe42da.jpg)


 I followed the steps in the link below.
https://forums.unrealengine.com/development-discussion/vr-ar-development/1494917-ue-4-20p4-arcore-image-database-cannot-build/page2
