### ISSUE TITLE
Does ARcore 1.6 support Vulkan in UE4? Or when can I support Vulkan?

### ISSUE THREAD

**Issue by a601336947** [google-ar/arcore-unreal-sdk#43]
I am using ARcore 1.6 to use Vulkan rendering in UE4. When I release the app, it flashes back. This makes me confused. I want to know if AR core 1.6 supports Vulkan rendering in UE4, or when can it be supported? I really need this Vulkan rendering because it gives me a better rendering effect, I hope you can answer me, thank you!
![1545359749 1](https://user-images.githubusercontent.com/21029334/50389750-01858980-0769-11e9-8432-79a6dcfce8f3.png)

**Comment by bopangzz** [comment]
ARCore currently doesn't support Vulkan on all platforms. You will have to use OpenGL if you want to use ARCore.

**Comment by jaggar28** [comment]
Hi, I've tried to use Vulkan API for gogole ARCore in UE4. It doesn't work. I'm using Samsung Galaxy S9+ btw. Any help will be appreciated. Thanks.
