### ISSUE TITLE
Augmented image is really slow to detect.

### ISSUE THREAD

**Issue by alexandreMarie** [google-ar/arcore-unreal-sdk#45]
Hi everyone,

My app is at its final stage before shipping. I still use Vuforia (and Unity) for Image tracking (and my app propose both with or without (you) image tracking) and I would like to know why is it so slow with ARCore. For the same image, Vuforia instantly detects the image where ARCore detects it in 5 or 6 seconds and I can't sell that. And I just wanted to know when ARCore will be production ready ? It's the only missing feature.

Best regards everyone.

**Comment by bopangzz** [comment]
ARCore session always enable 6 degree of freedom tracking and ARCore need to gather enough features and motion to estimate the 6dof pose of the device. This add to some time to the overall initialing.

To speed up the image detection in ARCore, you can specify the image physical width when you building the AugmentedImage database. This will help reduce the time it takes for ARCore to estimate the image pose.

**Comment by alexandreMarie** [comment]
Thanks @bopangzz. It has really fasten the image detection. 

Now I have another problem, it is to stabilize the session. I'm thinking about making an average transform of the currently detected image (because it will be always stationnary on a flat surface for my project) but it's another problem haha.

Thanks 

Alexandre
