### ISSUE TITLE
ARCore Session failed to start

### ISSUE THREAD

**Issue by Sage-SQ** [google-ar/arcore-unreal-sdk#46]
Ite could be caused by - Device is not compatible with ARCore. -ARCore APK failed to be installed.

**Comment by bopangzz** [comment]
Which version of Unreal are you using? Do you mind sending me the APK you built?

**Comment by Sage-SQ** [comment]
UE4.20
android-24,android-26,android-27
The file is too big to attach,How can I pass the apk to you?

**Comment by bopangzz** [comment]
Can you upload it on Google Drive and share the link here?

**Comment by Sage-SQ** [comment]
I don't have Google Drive, I can only send it to Baidu Cloud, I don't know if you can download it.

**Comment by Sage-SQ** [comment]
https://pan.baidu.com/s/1gAHCBNEUo8z02bP9He3reA

**Comment by Sage-SQ** [comment]
Has the APK been downloaded?

**Comment by bopangzz** [comment]
Yeah, I download it and looking at your apk, it looks like it is missing some manifest entry. When you build the apk in Unreal, did you explicitly uncheck the checkbox to not use gradle in your Project Settings-Android?

**Comment by Sage-SQ** [comment]
Yes, because if you don't uncheck it, the package is not successful.
But I just tested it again and it turned out to be a success.
Do you know why?

**Comment by Sage-SQ** [comment]
Maybe my NDK version is too old. I updated it before going to bed last night.
If you know the reason, please let me know, thank you.

**Comment by bopangzz** [comment]
I have to look at the Unreal output log to see why it failed to package when using gradle. You will need to use gradle when building for ARCore since otherwise it will missing manifest items in the final APK.

**Comment by Sage-SQ** [comment]
Do you know what the problem is?


![tim 20190116174250](https://user-images.githubusercontent.com/20352610/51240232-442c3180-19b6-11e9-81a7-d07bab902aae.png)

**Comment by Sage-SQ** [comment]
I have solved it, caused by the NDK version.
Thank you，again.

**Comment by Vraelir** [comment]
What NDK version is it now working with? And are you still using ant instead of gradle?

**Comment by Sage-SQ** [comment]
The latest version(NDK) worked.And you have to use the gradle,because the ARCore needed.
