### ISSUE TITLE
Arcore 1.2 1.4 1.6 with unreal 4.21 joystick problems

### ISSUE THREAD

**Issue by ParaO** [google-ar/arcore-unreal-sdk#47]
I have created 1st person example map. I have built it to andorid with joysticks on. Everything works fine...BUT...when I enable Google ARCore plugin joysticks prevent looking up and down?!?!? Everything else works like it should...what can i do? Are there any google developers reading these problems...? Can Someone help me...Thanks.

**Comment by bopangzz** [comment]
When you use ARCore, camera position and rotation are override by ARCore tracking, which is the general behavior in AR app. What is the use case you are trying to do with ARCore and joystick work together?

**Comment by ParaO** [comment]
> When you use ARCore, camera position and rotation are override by ARCore tracking, which is the general behavior in AR app. What is the use case you are trying to do with ARCore and joystick work together?

**Comment by ParaO** [comment]
bopangzz any news from this? Main thing for us is that we could close the arsession and all tracking when going to another level. I have tried to override everything from player controls,hud,gamemode, pawn etc. with no success...

**Comment by bopangzz** [comment]
I can help take a look sometime next week. Can you share a simple project
that could reproduce the issue? How is your pawn setup in your normal
scene? Try add a camera component in the pawn blueprint and uncheck the
lock to hmd option.

**Comment by ParaO** [comment]
Thanks for the quick response. Easy way of testing it...make a firstperson template. Enable arcore plugin 1.2 1.4 or 1.6 -> compile the project and try to look up or down. all the other movements are ok. I tried disabling the lock to hmd but the results remain the same.

**Comment by ParaO** [comment]
Hi bopangzz. Have you tried the plugin behavior yet? Sorry for the pressure but our client is waiting for the solution. If it is a big problem (which I dont belive...) I think we need to have a look to Unity...?Thanks again!

**Comment by ParaO** [comment]
Thanks a lot! Works like a charm😉. I ll be waiting for new relase as well...

**Comment by fredsa** [comment]
Fixed in 1.9.0
https://github.com/google-ar/arcore-unreal-sdk/releases
