### ISSUE TITLE
arcore data collection and processing

### ISSUE THREAD

**Issue by RH2** [google-ar/arcore-unreal-sdk#51]
> You must disclose **the use of ARCore and how it collects and processes data**, prominently in your application, easily accessible to users. You can do this by adding the following text on your main menu or notice screen: **"This application runs on ARCore, which is provided by Google LLC and governed by the Google Privacy Policy"**.

How exactly does this sdk use the data, and how does Google handle it? I think the readme could be more detailed, and an improved explanation would be useful.

**Comment by fredsa** [comment]
Please reference the published "Google Privacy Policy" (https://policies.google.com/privacy).
