### ISSUE TITLE
Question CloudARPin/MultiUser without internet connection

### ISSUE THREAD

**Issue by adnoh** [google-ar/arcore-unreal-sdk#53]
I'm evaluating the current AR Core in UE against AR Kit.
One of my questions/problems is a use case where I want to create a MultiUser experience in a WIFI WITHOUT InternetAccess. So one Phone is serving a UE Network session and the other clients join.
Now I'm wondering how to give Information like WorldOrigin and AR-PIN Transforms around.

I belive the CloudARPins work only with Google Cloud or can I replicate them with the normal Unreal Engine Networking API? If so how do I extract the informations from the AR Session?
In AR Kit I'm saving the current AR Session to a byte Array and replicate that over to another phone and import it back in and I have my Multiuser Experience ready to go. I haven't seen AR Core does provide this (export/import of AR Session), does it?

Thank you for Ideas and tipps.

**Comment by bopangzz** [comment]
You will need to have internet access when using CloudARPin, aka ARCore Cloud Anchor, since the host and resolve happens on the server side. ARCore currently doesn't support exporting session or map. However, using ARCore Cloud Anchor, you can share the same ARPin in the same physical spot between Android and iOS. For details, see: https://developers.google.com/ar/develop/unreal/cloud-anchors/overview-unreal

**Comment by adnoh** [comment]
Thank you for your answer bopangzz. 
When you mean "Server Side" I think you mean in the cloud? I would have Client and Server side in the terms of Unreal Networking in a local network (Server is Mapping the world and spawns actors).
If so, it is not possible for my case (Local WIFI network without Internet) to create a multiuser experience with arcore and I'm stuck with arkit because it can export the session information.

I hope google does implement it somehow, it would become really handy to save/load the arsession in a lot of use cases. I understand they have a cloud platform to sell, but not in every country or for every situation or location (think of large buildings not providing WIFI, so bad Mobile Signal) you can't expect to heave a fast or even steady internet connection.

Thanks for your answer again, I think this one could be closed.

**Comment by bopangzz** [comment]
Yeah, the cloud anchor need to be resolved using Google's cloud services. And thanks for the feedback, I will route your feature request to the team.
