### ISSUE TITLE
Unable to use HelloAR inside Android Studio Emulator

### ISSUE THREAD

**Issue by JohnsonJackblue** [google-ar/arcore-unreal-sdk#58]
Hello,

I recently compiled the 4.21-arcore and HelloAR project and tried to use the Emulator to run ARCore app.

I use NDK android-24 and SDK android-27 to package the x86 app (which support OpenGL ES 2.0-3.0), and my avd spec is Oreo API 27 x86 Android 8.1 (Google APIs) with Back Camera setup to Virtual Scene and Graphics setting set to Software.

I install ARCore_1.8.0.x86_for_emulator before HelloAR app.

I got this error message :
```
E/libEGL: called unimplemented OpenGL ES API
D/EGL_emulation: eglMakeCurrent: 0xe3f424a0: ver 3 0 (tinfo 0xd223fcd0)
D/EGL_emulation: eglMakeCurrent: 0xe3f42500: ver 3 0 (tinfo 0xe5903a40)
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glTexStorage2D:3423 GL error 0x500
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glTexStorage2D:3423 GL error 0x500
E/emuglGLESv2_enc: device/generic/goldfish-opengl/system/GLESv2_enc/GL2Encoder.cpp:s_glTexStorage2D:3423 GL error 0x500
```

**Comment by bopangzz** [comment]
Can you try x64 instead of x86? Last time I checked there is some issue with Android x86 in Unreal engine.

**Comment by JohnsonJackblue** [comment]
Thanks @bopangzz now it's works !

I used Pie API 28 x86_64 Android 9 (Google APIs) and compiled the app for x64, if someone encounter the same issue.
