### ISSUE TITLE
Augmented Images: Picture Frame Not Visible Anymore

### ISSUE THREAD

**Issue by Triplelexx** [google-ar/arcore-unreal-sdk#59]
I've been using the SDK for a few weeks. I built a project based off Augmented Images.
I was getting the detected image transform and succesfully spawning actors projected on top of the image.
Recently this stopped working for my project. I know the image is detected and am able to log the local to world transform changing when I move the piece of paper.
I am unable to see the actor on top anymore.
After much head scratching I resorted to downloading and trying the unedited project again.

I am unable to see the picture frame anymore. 
The widget shows that the image is detected and tracked, but no picture frame is visible.

I have not changed anything of the engine source.
I'm totally at a loss about this. The only possiblity I have now is the phone I'm testing with has downloaded a later version of ARCore and something has gone wrong.

The transform logging doesn't really help me. I have no reference for where those coordinates should be in my room.
It seems like the actors are indeed being spawned, but somewhere out of view.

Would anyone mind confirming if the project still works for them?

**Comment by elxpyder** [comment]
hi, how are you? did you find a solution for this? i had a working version too and now is not working, i have been doing a lot of tests but i cant make it work again.

**Comment by bopangzz** [comment]
Hi, which version of Unreal and GoogleARCore plugin you are using to built the app? Can you attach a logcat?

**Comment by Triplelexx** [comment]
4.21.2 of Unreal built from your fork with 1.7.0.
[Unreal_AI_logcat.txt](https://github.com/google-ar/arcore-unreal-sdk/files/3134446/Unreal_AI_logcat.txt)

**Comment by bopangzz** [comment]
Hmm, I can't reproduce the issue. The frame shows up fine for me. Have you tried build the HelloAR sample? Can you place object without problem there?

**Comment by Triplelexx** [comment]
Ok, thanks for the second opinion.
I'll do another round of testing.

**Comment by Triplelexx** [comment]
I am still unable to get the project working again.

@bopangzz Can you please confirm what device and Android version you tested with?

My phone is on Android 9. It would seem that I am not the only person who is unable to get Augmented Images working. Debugging this issue has cost me an unacceptable amount of time now.
I am very close to giving up and archiving the project, so I can get back to others.

**Comment by bopangzz** [comment]
This could be related to Android 9. I saw another issue report regards Android 9 and Unreal today. Which phone did you test on?

**Comment by Triplelexx** [comment]
Huawei P20 Pro

**Comment by bopangzz** [comment]
It would be good to know if HelloAR works for you. I tested with a Pixel 2 and Android 8. I will run some test on Android 9 today.

**Comment by Triplelexx** [comment]
I will have completed building in a few minutes and will edit this post with my result.

**Comment by elxpyder** [comment]
Hi, i dont know if this help but i am working in an Augmented Images project using ARCore with UE4.21.2 and testing in a Samsung Galaxy Note9. This is a project that was working and now i was doing some updates and is not working fine now so i dont know if it was an android update or something, also now i cant make it work with a new package, i have some testing and manage to detect the image but the tracking is not working well, the tracking is all messed up and takes a lot of time to get an acceptable tracking. I am using a get tracking state before get the transform but the issue is that always is detecting as tracked. I can add more info if that may help to find the issue i have or if help anyone to help to fix their issue. Thanks!

**Comment by Triplelexx** [comment]
@bopangzz It's been a week. I'm wondering when I should expect an update regarding this issue?

**Comment by bopangzz** [comment]
Sorry I am having trouble getting my device update to Android 9. The 1.9 ARCore app just come out, can you make sure you upgraded it and try run your app again?

**Comment by Triplelexx** [comment]
I can confirm Hello AR started working again, without re-installation. I haven't had a chance yet to test any further.
