### ISSUE TITLE
When image-tracking will be builtin in UE4?

### ISSUE THREAD

**Issue by sambuev** [google-ar/arcore-unreal-sdk#6]
Hello, I can't wait to be able to use ArCore with Image tracking option, I have heard about Vuforia for Unity, but never seen this for UE4, I wish new version of ArCore will support image-base tracking. 
Thank you.

**Comment by chaosemer** [comment]
Thank you for the feature request. Unfortunately, I have no dates I can share about this feature at this point in time.

Stay tuned!

**Comment by rasamaya** [comment]
You could try combining a score with unreal4ar

**Comment by rasamaya** [comment]
Sorry I'm on my phone and can't edit. Use arcore with unreal4ar

**Comment by sambuev** [comment]
Unreal4AR is not a steady solution and has significant limitations, I have tried it already, but the result is not that impressive. I saw demos from ARKit 1.5 with image-based tracking and it was just amazing, I hope ARCore 1.5 coming with this feature to Unreal Engine and it will blow the industry!

**Comment by chaosemer** [comment]
Thanks for your vote of confidence! Please do stay tuned, we are passionate about AR too! FYI, our next update won't be 1.5, it'll be 1.2. :)

**Comment by bopangzz** [comment]
The Augmented Image feature is added in ARCore Unreal SDK 1.2 release. See the developer guide here for details: https://developers.google.com/ar/develop/unreal/augmented-images/guide
