### ISSUE TITLE
arcore has stopped

### ISSUE THREAD

**Issue by bhin293** [google-ar/arcore-unreal-sdk#7]
I'm getting that message for the unreal demo, but the app still works if I touch around the error box. Here is the console log:
02-09 19:06:51.813: D/AndroidRuntime(23609): Shutting down VM
02-09 19:06:51.813: D/AndroidRuntime(23609): --------- beginning of crash
02-09 19:06:51.813: E/AndroidRuntime(23609): FATAL EXCEPTION: main
02-09 19:06:51.813: E/AndroidRuntime(23609): Process: com.google.ar.core, PID: 23609
02-09 19:06:51.813: E/AndroidRuntime(23609): java.lang.SecurityException: Signature check failed for com.google.ar.core
02-09 19:06:51.813: E/AndroidRuntime(23609): 	at android.os.Parcel.readException(Parcel.java:1693)
02-09 19:06:51.813: E/AndroidRuntime(23609): 	at android.os.Parcel.readException(Parcel.java:1646)
02-09 19:06:51.813: E/AndroidRuntime(23609): 	at vu.a(Unknown Source)
02-09 19:06:51.813: E/AndroidRuntime(23609): 	at uo.a(Unknown Source)
02-09 19:06:51.813: E/AndroidRuntime(23609): 	at abf.a(Unknown Source)
02-09 19:06:51.813: E/AndroidRuntime(23609): 	at abj.run(Unknown Source)
02-09 19:06:51.813: E/AndroidRuntime(23609): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
02-09 19:06:51.813: E/AndroidRuntime(23609): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-09 19:06:51.813: E/AndroidRuntime(23609): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
02-09 19:06:51.813: E/AndroidRuntime(23609): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
02-09 19:06:51.813: E/AndroidRuntime(23609): 	at xn.run(Unknown Source)
02-09 19:06:51.813: E/AndroidRuntime(23609): 	at java.lang.Thread.run(Thread.java:762)

**Comment by chaosemer** [comment]
What ARCore APK are you using? We have not seen this issue locally.

**Comment by bopangzz** [comment]
Closing the issue due to lack of response. Feel free to reopen it if you still have this problem.
