### ISSUE TITLE
"ARCore Session failed to start due to unsupported configuration" error with custom made images PLZ HELP

### ISSUE THREAD

**Issue by bryankim-ws** [google-ar/arcore-unreal-sdk#77]
I'm having this problem for days and it is driving me crazy.
Whenever I run Augmented Images template from ARCore dev page(https://developers.google.com/ar/dev...d-images/guide) I can deploy it, run it, and can see images are tracking properly. Cool.
HOWEVER, whenever I try to use my own image(Aruco markers) for mobile image tracking and this error message is popping up no matter what - "ARCore Session failed to start due to unsupported configuration".

Here are some repo steps that I tried:
1. Import a new image, create a data asset(ARCandidateImage), add the data asset to ARSession Config.
2. Replace the existing image for the new image.
3. Change config to GoogleARCoreSessionConfig and GoogleARCoreAugmentedImageDatabe, change to Start ARCore session inside the level blueprint.
4. When import a new image try jpg instead of png.
5. After importing a new image set the Compression Settings to RGBA and change texture group to UI (Tried out steps above with or without this setup)
6. Redo all the installation step including re-installing the engine.
7. Maybe I could get around if ARSessionErrorHandler isn't connected. Obviously no 

Can anyone please help me with what I'm doing wrong here?
Maybe there are certain image settings for image tracking?
When I try it out with a random image from a google search, it works :/

**Comment by bryankim-ws** [comment]
Failed due to not enough keypoints from target image.

**Comment by unig89** [comment]
Hi, how you have fix the Problem? :S
