### ISSUE TITLE
Missing Header File GoogleARCoreTypes.h

### ISSUE THREAD

**Issue by anthojohnson** [google-ar/arcore-unreal-sdk#9]
I keep getting this error when I try to open the project in Unreal Engine 4 (4.18.3 or 4.19 preview)
`Cannot open include file: 'GoogleARCoreTypes.h': No such file or directory`
![image](https://user-images.githubusercontent.com/36801381/36755183-43bc7cfe-1bc0-11e8-9501-010bd2d95aef.png)

**Comment by bopangzz** [comment]
Are you using the Epic version of Unreal Engine 4.18.3 or 4.19? If so, the latest version of the HelloAR project isn't compatible with the Epic version of Unreal Engine. You should use our forked version of Unreal Engine(https://github.com/google-ar-unreal/UnrealEngine) if you want to use the 1.0 version of ARCore SDK.

**Comment by anthojohnson** [comment]
Tyty - I will check that out.

**Comment by anthojohnson** [comment]
I get a 404 for that url - Do I need to request access?

**Comment by bopangzz** [comment]
You need to get Unreal Engine source code access. You can follow the guide here: https://developers.google.com/ar/develop/unreal/quickstart

**Comment by anthojohnson** [comment]
I see - I missed that part - in the quick start.  In case anyone else is having trouble.

Goto https://www.unrealengine.com/ 
Then Login to your account
Select your Personal From your account dropdown (top right on large formats) 
Then select CONNECTED ACCOUNTS and enter your github account name in the GITHUB portion
Then hit Save Changes

Then goto Github.com and login and await an invitation from Epic Games.  

TYVM bopangzz!
